# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit app --config=cloudbuild.yaml 
steps:
  # Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/repo-techub-python/hello-world-python:${SHORT_SHA}', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/repo-techub-python/hello-world-python','-f', 'Dockerfile']
    dir: 'app'  
    id: build
  # Run unit tests
  - name: europe-west1-docker.pkg.dev/$PROJECT_ID/repo-techub-python/hello-world-python
    entrypoint: python
    args: ["-m","pytest","unit_tests.py"]
    dir: 'app'
    id: test
  # Push docker image and save image digest for kritis check
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/repo-techub-python/hello-world-python:${SHORT_SHA}']
    id: push
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}",
        "--delivery-pipeline", "hello-world-python-pipeline",
        "--region", "europe-west1",
        "--annotations", "commitId=${REVISION_ID}",
        "--images", "hello-world-python=europe-west1-docker.pkg.dev/$PROJECT_ID/repo-techub-python/hello-world-python:${SHORT_SHA}"
      ]
