apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
spec:
  template:
    spec:
      containers:
          - name: hello-world-python
            env:
              - name: SITE_NAME
                value: "Population Stats Staging"